/*
  ─────────────────────────────────────────────────────────────
  YOUR CONTENT LIVES HERE.
  Edit, add, or remove entries below — the site rebuilds itself
  from this file. Everything is optional except `name` / `text`.

  The entries below are starter examples. Swap them for your own.
  ─────────────────────────────────────────────────────────────
*/

window.SITE = {
  owner: "Robert",
  title: "Cabinet of Inspiration",
  intro:
    "A living collection of the painters, makers, winemakers and words that shape how I see. Not a portfolio — a mirror.",

  artists: [
    {
      name: "Pierre Huyghe",
      medium: "Installation, film & living systems",
      era: "b. 1962",
      why: "The anchor of the whole list. Large, process-driven installations where organic and inorganic elements co-compose the work — Untilled and After ALife Ahead are the reference points.",
      link: "https://www.estherschipper.com/artists/41-pierre-huyghe/",
      tags: ["ecology", "living-systems", "conceptual"],
    },
    {
      name: "Bruce Nauman",
      medium: "Sculpture, video & neon",
      era: "b. 1941",
      why: "Post-conceptual lineage where language is a material condition, not a slogan. A steady presence near the top of the list for years.",
      link: "https://www.speronewestwater.com/artists/bruce-nauman",
      tags: ["language", "conceptual", "body"],
    },
    {
      name: "Theo Triantafyllidis",
      medium: "Digital art & simulation",
      era: "b. 1988",
      why: "Selective interest in tech and simulation — only when it's wedded to cosmology or cognition rather than novelty for its own sake.",
      link: "https://www.onassis.org/people/theo-triantafyllidis",
      tags: ["simulation", "digital", "performance"],
    },
    {
      name: "Lu Yang",
      medium: "Digital art, animation & video",
      era: "b. 1984",
      why: "Immersive digital work blending anime, gaming aesthetics, and Buddhist philosophy to explore identity, consciousness, and mortality.",
      link: "",
      tags: ["digital", "ritual", "avatar"],
    },
    {
      name: "Adrián Villar Rojas",
      medium: "Installation & sculpture",
      era: "b. 1980",
      why: "Monumental installations exploring extinction, multi-species boundaries, and speculative futures — organic and inorganic materials in one world-building gesture.",
      link: "https://www.moma.org/artists/42576-adrian-villar-rojas",
      tags: ["post-anthropocene", "installation", "decay"],
    },
    {
      name: "Marina Abramović",
      medium: "Performance",
      era: "b. 1946",
      why: "Foundational to the confrontational, endurance-based register I keep coming back to.",
      link: "https://www.skny.com/artists/marina-abramovic",
      tags: ["performance", "body", "endurance"],
    },
    {
      name: "Marlene Dumas",
      medium: "Painting",
      era: "b. 1953",
      why: "Figuration that carries autobiography and psychic weight rather than formal concerns.",
      link: "https://www.marlenedumas.nl/biography/",
      tags: ["figuration", "portrait", "psyche"],
    },
    {
      name: "Louise Bourgeois",
      medium: "Sculpture & drawing",
      era: "1911 – 2010",
      why: "Drawing and sculpture carrying body-sensation and psychic weight — a throughline for how I read figurative work generally.",
      link: "https://www.theeastonfoundation.org/louise-bourgeois",
      tags: ["body", "psyche", "sculpture"],
    },
    {
      name: "Wael Shawky",
      medium: "Film, performance & installation",
      era: "b. 1971",
      why: "Comfortable in the confrontational register — myth, history, and puppetry staged as contemporary critique.",
      link: "https://www.lissongallery.com/artists/wael-shawky",
      tags: ["myth", "history", "theatrical"],
    },
    {
      name: "Maurizio Cattelan",
      medium: "Sculpture & installation",
      era: "b. 1960",
      why: "Theatrical, mytho-historical, and provocative — not at odds with the more contemplative names on this list.",
      link: "https://whitney.org/artists/9300",
      tags: ["provocative", "humor", "conceptual"],
    },
    {
      name: "Trisha Donnelly",
      medium: "Sound, drawing, photography & performance",
      era: "b. 1974",
      why: "Mystical conceptual works exploring occult experience and material gesture across sound, drawing, and performance — encourages real contemplation.",
      link: "https://matthewmarks.com/artists/trisha-donnelly",
      tags: ["occult", "conceptual", "sound"],
    },
    {
      name: "Tracey Emin",
      medium: "Painting, drawing, neon & textile",
      era: "b. 1963",
      why: "Confessional, emotionally raw work across media — intimacy, loss, and vulnerability handled without distance.",
      link: "https://www.whitecube.com/artists/tracey-emin",
      tags: ["confessional", "body", "text"],
    },
    {
      name: "Mark Brusse",
      medium: "Assemblage sculpture",
      era: "b. 1937",
      why: "Wood and found-object assemblage exploring archaic symbols and East–West cross-cultural influence — eclectic materiality.",
      link: "https://www.centrepompidou.fr/en/ressources/personne/cTBB6o",
      tags: ["assemblage", "wood", "archaic"],
    },
    {
      name: "Klára Hošnedlová",
      medium: "Sculpture & installation",
      era: "b. 1990",
      why: "Sculpture that leaks, breathes, or refuses containment — part of the abject/metabolic cluster I track closely.",
      link: "https://www.whitecube.com/artists/kl%C3%A1ra-hosnedlov%C3%A1",
      tags: ["craft", "biomorphic", "installation"],
    },
    {
      name: "Mire Lee",
      medium: "Sculpture & kinetic installation",
      era: "b. 1988",
      why: "Sculpture that leaks, breathes, sweats, decays — the clearest current example of the abject/metabolic thread for me.",
      link: "https://tinakimgallery.com/artists/71-mire-lee/",
      tags: ["abject", "kinetic", "metabolic"],
    },
    {
      name: "Agata Ingarden",
      medium: "Sculpture & installation",
      era: "b. 1994",
      why: "Part of the same body-material cluster as Lee and Hošnedlová — materials treated as if alive.",
      link: "https://futuregenerationartprize.org/en/persons-fgap/artist-en/agata-ingarden",
      tags: ["metabolic", "materials", "sculpture"],
    },
    {
      name: "Sun Yuan & Peng Yu",
      medium: "Installation & kinetic sculpture",
      era: "b. 1972 / 1974",
      why: "Confrontational, ethically uncomfortable work in the same register as Cattelan and Shawky.",
      link: "https://www.galleriacontinua.com/artists/sun-yuan-peng-yu-73",
      tags: ["provocative", "machine", "installation"],
    },
    {
      name: "Ryan Gander",
      medium: "Conceptual art & sculpture",
      era: "b. 1976",
      why: "Conceptual practice where ideas and absence are as much material as the objects themselves.",
      link: "https://www.lissongallery.com/artists/ryan-gander",
      tags: ["conceptual", "language", "humor"],
    },
    {
      name: "Maria Lassnig",
      medium: "Painting",
      era: "1919 – 2014",
      why: "TODO",
      link: "",
      tags: ["body", "figuration", "psyche"],
    },
    {
      name: "Christoph Büchel",
      medium: "Installation",
      era: "b. 1966",
      why: "TODO",
      link: "",
      tags: ["installation", "political", "immersive"],
    },
    {
      name: "Cyprien Gaillard",
      medium: "Film, photography & installation",
      era: "b. 1980",
      why: "TODO",
      link: "https://gladstonegallery.com/artist/cyprien-gaillard/",
      tags: ["entropy", "ruins", "film"],
    },
    {
      name: "Yunchul Kim",
      medium: "Installation & media art",
      era: "b. 1970",
      why: "TODO",
      link: "https://ocula.com/artists/yunchul-kim/",
      tags: ["science", "cosmology", "fluid"],
    },
    {
      name: "Paul McCarthy",
      medium: "Performance, sculpture & installation",
      era: "b. 1945",
      why: "TODO",
      link: "https://www.hauserwirth.com/artists/2796-paul-mccarthy/",
      tags: ["abject", "provocative", "performance"],
    },
    {
      name: "Uffe Isolotto",
      medium: "Sculpture & installation",
      era: "b. 1976",
      why: "TODO",
      link: "https://uffeisolotto.com",
      tags: ["post-human", "hyperreal", "sculpture"],
    },
    {
      name: "Matthias Garcia",
      medium: "Painting",
      era: "b. 1994",
      why: "TODO",
      link: "https://www.galeriesultana.com/shows/fakelore",
      tags: ["figuration", "painting"],
    },
    {
      name: "Berlinde De Bruyckere",
      medium: "Sculpture",
      era: "b. 1964",
      why: "TODO",
      link: "https://www.hauserwirth.com/artists/2782-berlinde-de-bruyckere/",
      tags: ["flesh", "wax", "abject"],
    },
    {
      name: "Ivana Bašić",
      medium: "Sculpture",
      era: "b. 1986",
      why: "TODO",
      link: "https://www.marlboroughnewyork.com/artists/ivana-basic",
      tags: ["body", "metamorphosis", "breath"],
    },
    {
      name: "Anne Imhof",
      medium: "Performance, painting & installation",
      era: "b. 1978",
      why: "TODO",
      link: "https://spruethmagers.com/artists/anne-imhof/",
      tags: ["performance", "body", "installation"],
    },
    {
      name: "Ugo Schiavi",
      medium: "Sculpture",
      era: "b. 1987",
      why: "TODO",
      link: "https://www.double-v-gallery.com/ugo-schiavi",
      tags: ["archaeology", "plants", "sculpture"],
    },
    {
      name: "Pol Taburet",
      medium: "Painting & sculpture",
      era: "b. 1997",
      why: "TODO",
      link: "https://www.balicehertling.com/exhibitions/11-pol-taburet-echoes-from-us/",
      tags: ["figuration", "occult", "painting"],
    },
    {
      name: "Wols",
      medium: "Painting, drawing & photography",
      era: "1913 – 1951",
      why: "TODO",
      link: "",
      tags: ["abstract", "informel", "psyche"],
    },
    {
      name: "Rebecca Ackroyd",
      medium: "Sculpture & drawing",
      era: "b. 1987",
      why: "TODO",
      link: "https://www.timothytaylor.com/artists/rebecca-ackroyd/",
      tags: ["body", "memory", "sculpture"],
    },
    {
      name: "Isabelle Andriessen",
      medium: "Sculpture",
      era: "b. 1986",
      why: "TODO",
      link: "https://www.frontart.org/artists/andriessen",
      tags: ["metabolic", "materials", "sculpture"],
    },
    {
      name: "Rachel Rose",
      medium: "Film & installation",
      era: "b. 1986",
      why: "TODO",
      link: "https://www.pilarcorrias.com/artists/32-rachel-rose/cv/",
      tags: ["film", "landscape", "belief"],
    },
    {
      name: "Holly Herndon & Mat Dryhurst",
      medium: "AI, sound & performance",
      era: "b. 1980 / 1984",
      why: "TODO",
      link: "https://whitney.org/exhibitions/xhairymutantx",
      tags: ["ai", "sound", "digital"],
    },
    {
      name: "Lou Cantor",
      medium: "Installation & video (collective)",
      era: "contemporary",
      why: "TODO",
      link: "",
      tags: ["collective", "installation"],
    },
    {
      name: "Allora & Calzadilla",
      medium: "Sculpture, performance & installation",
      era: "b. 1974 / 1971",
      why: "TODO",
      link: "https://www.crousel.com/en/artist/jennifer-allora-guillermo-calzadilla/",
      tags: ["conceptual", "political", "sound"],
    },
    {
      name: "Maria Hassabi",
      medium: "Performance & choreography",
      era: "b. 1973",
      why: "TODO",
      link: "https://www.tate.org.uk/art/artists/maria-hassabi-31491",
      tags: ["performance", "body", "stillness"],
    },
    {
      name: "Bojan Šarčević",
      medium: "Sculpture, film & collage",
      era: "b. 1974",
      why: "TODO",
      link: "https://galeriefrankelbaz.com/artists/45-bojan-sarcevic/",
      tags: ["sculpture", "minimal", "film"],
    },
    {
      name: "Mimosa Echard",
      medium: "Installation & mixed media",
      era: "b. 1986",
      why: "TODO",
      link: "https://www.crousel.com/en/artist/mimosa-echard-S8DOGX/",
      tags: ["organic", "materials", "installation"],
    },
    {
      name: "Camille Henrot",
      medium: "Film, sculpture & drawing",
      era: "b. 1978",
      why: "TODO",
      link: "https://www.hauserwirth.com/artists/35528-camille-henrot/",
      tags: ["film", "anthropology", "drawing"],
    },
    {
      name: "Rosa Barba",
      medium: "Film & installation",
      era: "b. 1972",
      why: "TODO",
      link: "https://www.estherschipper.com/artists/118-rosa-barba/",
      tags: ["film", "landscape", "time"],
    },
    {
      name: "Ambera Wellmann",
      medium: "Painting",
      era: "b. 1982",
      why: "TODO",
      link: "https://www.hauserwirth.com/artists/ambera-wellmann/",
      tags: ["figuration", "body", "painting"],
    },
    {
      name: "Ho Tzu Nyen",
      medium: "Film & video installation",
      era: "b. 1976",
      why: "TODO",
      link: "https://www.guggenheim.org/artwork/artist/ho-tzu-nyen",
      tags: ["film", "history", "myth"],
    },
    {
      name: "Ed Atkins",
      medium: "Video, CGI & writing",
      era: "b. 1982",
      why: "TODO",
      link: "https://www.tate.org.uk/art/artists/ed-atkins-15601",
      tags: ["digital", "language", "body"],
    },
    {
      name: "Philippe Parreno",
      medium: "Film & installation",
      era: "b. 1964",
      why: "TODO",
      link: "https://www.pilarcorrias.com/artists/30-philippe-parreno/biography/",
      tags: ["film", "installation", "time"],
    },
    {
      name: "Théo Mercier",
      medium: "Sculpture, installation & stage",
      era: "b. 1984",
      why: "TODO",
      link: "https://theomercier.com/en/about/",
      tags: ["sculpture", "theatrical", "anthropology"],
    },
    {
      name: "Dozie Kanu",
      medium: "Sculpture & design",
      era: "b. 1993",
      why: "TODO",
      link: "https://www.doziekanu.com/",
      tags: ["design", "sculpture", "identity"],
    },
    {
      name: "Klara Kristalova",
      medium: "Ceramic sculpture",
      era: "b. 1967",
      why: "TODO",
      link: "https://www.perrotin.com/en/artists/Klara_Kristalova/29",
      tags: ["ceramics", "folklore", "figurative"],
    },
    {
      name: "Sarah Anaïs Desbenoit",
      medium: "Sculpture & installation",
      era: "contemporary",
      why: "TODO",
      link: "",
      tags: ["sculpture"],
    },
    {
      name: "Alia Farid",
      medium: "Sculpture, film & installation",
      era: "b. 1985",
      why: "TODO",
      link: "https://sfeir-semler.com/artists/artists/alia-farid",
      tags: ["diaspora", "film", "sculpture"],
    },
    {
      name: "Borgial",
      medium: "Painting & drawing",
      era: "b. 1994",
      why: "TODO",
      link: "",
      tags: ["painting"],
    },
    {
      name: "Leiko Ikemura",
      medium: "Painting & sculpture",
      era: "b. 1951",
      why: "TODO",
      link: "https://www.lissongallery.com/artists/leiko-ikemura",
      tags: ["figuration", "landscape", "sculpture"],
    },
    {
      name: "Marguerite Humeau",
      medium: "Sculpture & installation",
      era: "b. 1986",
      why: "TODO",
      link: "https://www.whitecube.com/artists/marguerite-humeau",
      tags: ["speculative", "biology", "sculpture"],
    },
    {
      name: "Josèfa Ntjam",
      medium: "Installation, film & photomontage",
      era: "b. 1992",
      why: "TODO",
      link: "https://nicoletticontemporary.com/artist/josefa-ntjam/",
      tags: ["afrofuturism", "myth", "digital"],
    },
    {
      name: "Ian Cheng",
      medium: "Live simulation & digital art",
      era: "b. 1984",
      why: "TODO",
      link: "https://gladstonegallery.com/artist/ian-cheng/",
      tags: ["simulation", "ai", "digital"],
    },
    {
      name: "Peter Doig",
      medium: "Painting",
      era: "b. 1959",
      why: "TODO",
      link: "https://peterdoig.com/",
      tags: ["landscape", "dreamlike", "painting"],
    },
    {
      name: "Justine Emard",
      medium: "Video, photography & AI",
      era: "contemporary",
      why: "TODO",
      link: "https://justineemard.com/",
      tags: ["ai", "robotics", "video"],
    },
    {
      name: "Salman Toor",
      medium: "Painting",
      era: "b. 1983",
      why: "TODO",
      link: "https://www.luhringaugustine.com/artists/salman-toor",
      tags: ["figuration", "queer", "painting"],
    },
    {
      name: "Wang Shui",
      medium: "Painting, sculpture & video",
      era: "b. 1986",
      why: "TODO",
      link: "https://highart.fr/artists/wangshui/",
      tags: ["abstract", "digital", "painting"],
    },
    {
      name: "Ai Weiwei",
      medium: "Sculpture, installation & activism",
      era: "b. 1957",
      why: "TODO",
      link: "https://www.guggenheim.org/artwork/artist/ai-weiwei",
      tags: ["political", "conceptual", "installation"],
    },
    {
      name: "Peter Buggenhout",
      medium: "Sculpture",
      era: "b. 1963",
      why: "TODO",
      link: "https://www.axel-vervoordt.com/gallery/artists/peter-buggenhout",
      tags: ["abject", "dust", "sculpture"],
    },
    {
      name: "Lionel Maunz",
      medium: "Sculpture",
      era: "contemporary",
      why: "TODO",
      link: "https://www.moma.org/artists/47886-lionel-maunz",
      tags: ["sculpture", "abject"],
    },
    {
      name: "Bianca Bondi",
      medium: "Installation & sculpture",
      era: "b. 1986",
      why: "TODO",
      link: "https://www.mor-charpentier.com/artist/bianca-bondi-2/",
      tags: ["ritual", "chemistry", "installation"],
    },
    {
      name: "Anna Uddenberg",
      medium: "Sculpture & performance",
      era: "b. 1982",
      why: "TODO",
      link: "https://www.k-t-z.com/artists/39-anna-uddenberg/",
      tags: ["body", "sculpture", "performance"],
    },
    {
      name: "Anastasia Sosunova",
      medium: "Installation, video & print",
      era: "b. 1993",
      why: "TODO",
      link: "https://www.artsy.net/artist/anastasia-sosunova",
      tags: ["ritual", "installation", "baltic"],
    },
    {
      name: "Florian Krewer",
      medium: "Painting",
      era: "b. 1986",
      why: "TODO",
      link: "https://www.michaelwerner.com/artists/florian-krewer",
      tags: ["figuration", "painting", "nocturne"],
    },
    {
      name: "George Rouy",
      medium: "Painting",
      era: "b. 1994",
      why: "TODO",
      link: "https://www.hauserwirth.com/artists/george-rouy/",
      tags: ["figuration", "body", "painting"],
    },
    {
      name: "Issy Wood",
      medium: "Painting",
      era: "b. 1993",
      why: "TODO",
      link: "https://ocula.com/artists/issy-wood/",
      tags: ["figuration", "portrait", "painting"],
    },
    {
      name: "Amoako Boafo",
      medium: "Painting",
      era: "b. 1984",
      why: "TODO",
      link: "https://gagosian.com/artists/amoako-boafo/",
      tags: ["portrait", "figuration", "painting"],
    },
    {
      name: "Adrian Ghenie",
      medium: "Painting",
      era: "b. 1977",
      why: "TODO",
      link: "https://ropac.net/artists/44-adrian-ghenie/",
      tags: ["figuration", "history", "painting"],
    },
    {
      name: "Michelle Uckotter",
      medium: "Painting",
      era: "b. 1992",
      why: "TODO",
      link: "https://www.matthewbrowngallery.com/artists/michelle-uckotter",
      tags: ["figuration", "uncanny", "painting"],
    },
    {
      name: "Miriam Cahn",
      medium: "Painting",
      era: "b. 1949",
      why: "TODO",
      link: "https://ocula.com/artists/miriam-cahn/",
      tags: ["body", "figuration", "political"],
    },
    {
      name: "Michael Armitage",
      medium: "Painting",
      era: "b. 1984",
      why: "TODO",
      link: "https://www.davidzwirner.com/artists/michael-armitage",
      tags: ["figuration", "myth", "painting"],
    },
    {
      name: "Dora Jeridi",
      medium: "Painting",
      era: "b. 1988",
      why: "TODO",
      link: "https://marianneboeskygallery.com/artists/502-dora-jeridi/biography/",
      tags: ["figuration", "painting"],
    },
    {
      name: "Liza Lacroix",
      medium: "Painting",
      era: "b. 1988",
      why: "TODO",
      link: "https://magentaplains.com/artists/liza-lacroix/bio",
      tags: ["gestural", "painting"],
    },
    {
      name: "Selome Muleta",
      medium: "Painting",
      era: "b. 1992",
      why: "TODO",
      link: "https://addisfineart.com/artists/109-selome-muleta/biography/",
      tags: ["figuration", "spectral", "painting"],
    },
    {
      name: "Ser Serpas",
      medium: "Painting & sculpture",
      era: "b. 1995",
      why: "TODO",
      link: "https://ocula.com/artists/ser-serpas/",
      tags: ["figuration", "found-object", "painting"],
    },
    {
      name: "Karol Palczak",
      medium: "Painting",
      era: "b. 1987",
      why: "TODO",
      link: "",
      tags: ["figuration", "spectral", "painting"],
    },
    {
      name: "Tobias Pils",
      medium: "Painting",
      era: "b. 1971",
      why: "TODO",
      link: "https://www.presenhuber.com/exhibitions/tobias-pils",
      tags: ["painting", "analytic"],
    },
    {
      name: "Magnus Plessen",
      medium: "Painting",
      era: "b. 1967",
      why: "TODO",
      link: "https://www.gerhardsengerner.com/magnus-plessen-biography",
      tags: ["figuration", "analytic", "painting"],
    },
    {
      name: "Andro Wekua",
      medium: "Painting & sculpture",
      era: "b. 1977",
      why: "TODO",
      link: "https://www.gladstonegallery.com/artist/andro-wekua/works",
      tags: ["memory", "figuration", "sculpture"],
    },
    {
      name: "Brook Hsu",
      medium: "Painting",
      era: "b. 1987",
      why: "TODO",
      link: "https://gladstonegallery.com/artist/brook-hsu/",
      tags: ["spectral", "painting"],
    },
    {
      name: "Walter Pichler",
      medium: "Sculpture, drawing & architecture",
      era: "1936 – 2012",
      why: "TODO",
      link: "https://galerie-krinzinger.at/artists/walter-pichler-daf17832/",
      tags: ["ritual", "sculpture", "body"],
    },
    {
      name: "Sydney Cain",
      medium: "Painting & drawing",
      era: "b. 1991",
      why: "TODO",
      link: "https://renabranstengallery.com/artists/sydney-cain/",
      tags: ["spectral", "figuration", "drawing"],
    },
    {
      name: "Xinyi Cheng",
      medium: "Painting",
      era: "b. 1989",
      why: "TODO",
      link: "https://matthewmarks.com/artists/xinyi-cheng/information/biography",
      tags: ["intimacy", "figuration", "painting"],
    },
    {
      name: "Max Ernst",
      medium: "Painting, collage & sculpture",
      era: "1891 – 1976",
      why: "TODO",
      link: "https://www.guggenheim.org/artwork/artist/max-ernst",
      tags: ["surrealism", "process", "cosmology"],
    },
    {
      name: "Dominique Gonzalez-Foerster",
      medium: "Installation, film & performance",
      era: "b. 1965",
      why: "TODO",
      link: "https://www.303gallery.com/artists/dominique-gonzalez-foerster",
      tags: ["installation", "film", "immersive"],
    },
    {
      name: "Julie Mehretu",
      medium: "Painting",
      era: "b. 1970",
      why: "TODO",
      link: "https://www.moma.org/collection/artists/25414",
      tags: ["abstract", "layered", "painting"],
    },
    {
      name: "Inès di Folco Jemni",
      medium: "Painting",
      era: "b. 1993",
      why: "TODO",
      link: "https://ocula.com/artists/ines-di-folco-jemni/",
      tags: ["mystical", "ritual", "painting"],
    },
    {
      name: "Shadi Al-Atallah",
      medium: "Painting",
      era: "b. 1994",
      why: "TODO",
      link: "https://kristinhjellegjerde.com/artists/458/overview/",
      tags: ["figuration", "self-portrait", "painting"],
    },
    {
      name: "Théo Viardin",
      medium: "Painting",
      era: "b. 1992",
      why: "TODO",
      link: "https://kandlhofer.com/artists/312-theo-viardin",
      tags: ["mutant", "spectral", "painting"],
    },
    {
      name: "Claudia Koh",
      medium: "Painting",
      era: "b. 1999",
      why: "TODO",
      link: "https://www.aucart.com/artists/claudia-koh/",
      tags: ["figuration", "painting"],
    },
    {
      name: "August Joost",
      medium: "Painting",
      era: "b. 2003",
      why: "TODO",
      link: "https://noba.ac/en/artist/august-joost/",
      tags: ["figuration", "painting", "baltic"],
    },
    {
      name: "Jan Eustachy Wolski",
      medium: "Painting",
      era: "b. 1997",
      why: "TODO",
      link: "https://www.instagram.com/jan__wolski/",
      tags: ["figuration", "painting"],
    },
    {
      name: "Julia Kowalska",
      medium: "Painting",
      era: "b. 1998",
      why: "TODO",
      link: "https://www.coulisse-gallery.com/artist/julia-kowalska",
      tags: ["blur", "body", "painting"],
    },
    {
      name: "Taiyo Shimizu Larenas",
      medium: "Painting",
      era: "contemporary",
      why: "TODO",
      link: "https://taiyoshimizularenas.nl/about.html",
      tags: ["apparition", "figuration", "painting"],
    },
    {
      name: "Sergio Miguel",
      medium: "Painting",
      era: "b. 1992",
      why: "Technique and themes solid and deep.",
      link: "https://companygallery.us/artists/sergio-miguel",
      tags: ["figuration", "painting"],
    },
    {
      name: "Anna Ruth",
      medium: "Painting",
      era: "b. 1994",
      why: "TODO",
      link: "https://grimmgallery.com/artists/268-anna-ruth/",
      tags: ["figuration", "painting"],
    },
    {
      name: "Evelyn Plaschg",
      medium: "Painting",
      era: "b. 1988",
      why: "TODO",
      link: "https://emanuellayr.com/evelyn-plaschg/",
      tags: ["figuration", "painting"],
    },
    {
      name: "Djabril Boukhenaïssi",
      medium: "Painting",
      era: "b. 1992",
      why: "TODO",
      link: "https://marianeibrahim.com/artists/102-djabril-boukhenaissi/",
      tags: ["figuration", "nocturne", "painting"],
    },
    {
      name: "Lulua Alyahya",
      medium: "Painting",
      era: "b. 1998",
      why: "TODO",
      link: "https://athrart.com/artists/49-lulua-alyahya/biography/",
      tags: ["figuration", "painting"],
    },
    {
      name: "Okiki Akinfe",
      medium: "Painting",
      era: "b. 1999",
      why: "TODO",
      link: "https://www.peeruk.org/okiki-akinfe",
      tags: ["figuration", "painting"],
    },
    {
      name: "Justin de Verteuil",
      medium: "Painting",
      era: "b. 1990",
      why: "TODO",
      link: "https://www.sieshoeke.com/artists/justin-de-verteuil",
      tags: ["figuration", "painting"],
    },
    {
      name: "Taína H. Cruz",
      medium: "Painting",
      era: "b. 1998",
      why: "TODO",
      link: "https://tainacruz.com/Bio",
      tags: ["figuration", "painting"],
    },
    {
      name: "Joanna Woś",
      medium: "Painting",
      era: "b. 1991",
      why: "TODO",
      link: "https://galeriawschod.com/artists/joanna-wos/",
      tags: ["figuration", "painting"],
    },
    {
      name: "Yasmeen Abdullah",
      medium: "Painting",
      era: "b. 1992",
      why: "TODO",
      link: "https://www.arakcollection.com/artists/yasmeen-abdullah",
      tags: ["figuration", "painting"],
    },
    {
      name: "Kira Scerbin",
      medium: "Painting",
      era: "b. 1991",
      why: "TODO",
      link: "https://www.kingsleapfinearts.com/artists/kira-scerbin",
      tags: ["figuration", "painting"],
    },
    {
      name: "Alessandro Fogo",
      medium: "Painting",
      era: "b. 1992",
      why: "TODO",
      link: "https://www.cassinaprojects.com/cassina-projects/artists/alessandro-fogo/",
      tags: ["figuration", "painting"],
    },
    {
      name: "Łukasz Stokłosa",
      medium: "Painting",
      era: "b. 1986",
      why: "TODO",
      link: "http://www.lukaszstoklosa.com/bio-2/",
      tags: ["interiors", "history", "painting"],
    },
    {
      name: "Christopher Samuel Idowu",
      medium: "Painting",
      era: "b. 1995",
      why: "TODO",
      link: "https://ko-artspace.com/exhibitions/46-christopher-samuel-idowu-the-secret-place/",
      tags: ["spectral", "figuration", "painting"],
    },
    {
      name: "Lotte Maiwald",
      medium: "Painting",
      era: "b. 1988",
      why: "TODO",
      link: "https://www.sieshoeke.com/artists/lotte-maiwald",
      tags: ["figuration", "painting"],
    },
    {
      name: "Neïla Czermak Ichti",
      medium: "Painting & drawing",
      era: "b. 1996",
      why: "TODO",
      link: "https://galerieannebarrault.com/en/artiste/neila-czermak-ichti/",
      tags: ["figuration", "uncanny", "painting"],
    },
    {
      name: "Maitha Abdalla",
      medium: "Painting, sculpture & performance",
      era: "b. 1989",
      why: "TODO",
      link: "https://www.tabariartspace.com/artists/154-maitha-abdalla/biography/",
      tags: ["myth", "figuration", "painting"],
    },
    {
      name: "Asami Shoji",
      medium: "Painting",
      era: "b. 1988",
      why: "TODO",
      link: "https://ghebaly.com/exhibitions/195-elizabeth-glaessner-asami-shoji-oda-iselin-snderland/",
      tags: ["figuration", "painting"],
    },
    {
      name: "Liang Fu",
      medium: "Painting",
      era: "b. 1993",
      why: "Really stood out.",
      link: "https://www.nicodimgallery.com/artists/liang-fu",
      tags: ["mineral", "frottage", "painting"],
    },
    {
      name: "Nika Kutateladze",
      medium: "Painting",
      era: "b. 1989",
      why: "TODO",
      link: "https://galleryartbeat.com/en/artist/exhibitions/article/129",
      tags: ["matter", "painting"],
    },
    {
      name: "Evangeline Turner",
      medium: "Painting",
      era: "b. 1996",
      why: "TODO",
      link: "https://www.asquire.ltd/evangeline-turner-i-love-you-with-all-my-bowels",
      tags: ["eschatology", "figuration", "painting"],
    },
    {
      name: "Cily Gonzalez",
      medium: "Painting on wood",
      era: "b. 2000",
      why: "TODO",
      link: "https://www.instagram.com/cily.gonzalez/",
      tags: ["matter", "buried", "painting"],
    },
    {
      name: "Srijon Chowdhury",
      medium: "Painting",
      era: "b. 1987",
      why: "TODO",
      link: "https://anatebgi.com/exhibitions/solo-exhibition/",
      tags: ["devotional", "figuration", "painting"],
    },
    {
      name: "Ernst Yohji Jaeger",
      medium: "Painting",
      era: "b. 1990",
      why: "TODO",
      link: "https://galeriecrevecoeur.com/artists/ernst-yohji-jaeger",
      tags: ["twilight", "figuration", "painting"],
    },
    {
      name: "Emanuel de Carvalho",
      medium: "Painting",
      era: "b. 1984",
      why: "TODO",
      link: "https://www.gathering.london/artists/emanuel-de-carvalho",
      tags: ["figuration", "painting"],
    },
    {
      name: "Baixuan Chen",
      medium: "Painting",
      era: "b. 1997",
      why: "TODO",
      link: "https://jan-kaps.com/exhibitions/baixuan-chen/",
      tags: ["figuration", "painting"],
    },
    {
      name: "Tenki Hiramatsu",
      medium: "Painting",
      era: "b. 1986",
      why: "TODO",
      link: "https://www.barbaraseiler.ch/exhibitions/tenki-hiramatsu/",
      tags: ["figuration", "painting"],
    },
    {
      name: "Nicholas Grafia",
      medium: "Painting",
      era: "b. 1990",
      why: "TODO",
      link: "https://peresprojects.com/artists/44-nicholas-grafia/",
      tags: ["figuration", "painting"],
    },
    {
      name: "Justine Neuberger",
      medium: "Painting",
      era: "b. 1993",
      why: "TODO",
      link: "https://www.climagallery.com/artist/justine-neuberger/",
      tags: ["figuration", "painting"],
    },
    {
      name: "Alison Yip",
      medium: "Painting",
      era: "contemporary",
      why: "TODO",
      link: "https://noahklink.com/artists/alison-yip",
      tags: ["figuration", "painting"],
    },
    {
      name: "Rexy Tseng",
      medium: "Painting & sculpture",
      era: "b. 1986",
      why: "TODO",
      link: "https://rexytseng.com/who",
      tags: ["figuration", "painting"],
    },
    {
      name: "Yi To",
      medium: "Painting",
      era: "b. 1995",
      why: "TODO",
      link: "https://www.mapafineart.com/artists/yi-to/",
      tags: ["figuration", "painting"],
    },
    {
      name: "Lucía Vidales",
      medium: "Painting",
      era: "b. 1986",
      why: "TODO",
      link: "https://www.karen-huber.com/artists/lucia-vidales",
      tags: ["figuration", "painting"],
    },
    {
      name: "Nzubechukwu Ozoemena",
      medium: "Painting",
      era: "b. 1999",
      why: "TODO",
      link: "https://www.artsy.net/artist/ozoemena-nzubechukwu",
      tags: ["spectral", "figuration", "painting"],
    },
    {
      name: "Emma Rose Schwartz",
      medium: "Painting",
      era: "contemporary",
      why: "TODO",
      link: "https://www.brunettecoleman.com/fairs/frieze-london-2025-emma-rose-schwartz",
      tags: ["figuration", "painting"],
    },
    {
      name: "Veronika Hapchenko",
      medium: "Painting",
      era: "contemporary",
      why: "TODO",
      link: "https://importexport.art/veronika-hapchenko-cv/",
      tags: ["figuration", "painting"],
    },
    {
      name: "Talar Aghbashian",
      medium: "Painting",
      era: "b. 1981",
      why: "TODO",
      link: "https://www.marfaprojects.com/artists/36-talar-aghbashian/biography/",
      tags: ["figuration", "painting"],
    },
    {
      name: "Shailee Mehta",
      medium: "Painting",
      era: "b. 1998",
      why: "TODO",
      link: "https://www.theresidencegallery.com/shailee-mehta",
      tags: ["figuration", "painting"],
    },
    {
      name: "Zuzanna Bartoszek",
      medium: "Painting",
      era: "b. 1993",
      why: "TODO",
      link: "https://cfa-gallery.com/artists/zuzanna-bartoszek-9e3e506b/",
      tags: ["figuration", "painting"],
    },
    {
      name: "Caja Boogers",
      medium: "Painting",
      era: "b. 2001",
      why: "TODO",
      link: "https://www.cajaboogers.com/info/",
      tags: ["archive", "figuration", "painting"],
    },
    {
      name: "Xingzi Gu",
      medium: "Painting",
      era: "contemporary",
      why: "TODO",
      link: "https://lubov.nyc/xingzi-gu",
      tags: ["stain", "figuration", "painting"],
    },
    {
      name: "James Nepaulsingh",
      medium: "Painting",
      era: "contemporary",
      why: "TODO",
      link: "",
      tags: ["figuration", "painting"],
    },
  ],

  winemakers: [
    // ── Tasted ──────────────────────────────────────────────
    {
      name: "Apostolos Thymiopoulos",
      group: "Tasted",
      estate: "Thymiopoulos Vineyards",
      region: "Naoussa (Trilofos), Macedonia",
      country: "Greece",
      grapes: "Xinomavro",
      favorite: "Vrana Petra 2019",
      why: "A bottle of Vrana Petra 2019 stayed with me — enough that it became one of the reference wines I'm building my cellar around. Xinomavro from Trilofos sits at the very centre of that idea.",
      link: "https://www.thymiopoulosvineyards.gr",
      tags: ["organic", "single vineyard"],
    },
    {
      name: "Christophe Abbet",
      group: "Tasted",
      estate: "Cave Christophe Abbet et Fils",
      region: "Martigny, Valais",
      country: "Switzerland",
      grapes: "Marsanne, Petite Arvine, Gamay",
      favorite: "Marsanne 2019 (bottle 259/1300)",
      why: "I was struck by the texture and tension of his Marsanne 2019, grown on century-old vines on granite.",
      link: "https://www.abbet-vins.ch",
      tags: ["old vines", "granite", "natural"],
    },
    {
      name: "Jonatan García",
      group: "Tasted",
      estate: "Suertes del Marqués",
      region: "Valle de la Orotava, Tenerife",
      country: "Spain",
      grapes: "Listán Blanco, Listán Negro",
      favorite: "Edición 1 Listán Blanco 2022 (bottle 078/640)",
      why: "TODO",
      link: "https://www.suertesdelmarques.com",
      tags: ["volcanic", "old vines"],
    },

    // ── Piedmont & Valtellina ───────────────────────────────
    {
      name: "Augusto Cappellano",
      group: "Piedmont & Valtellina",
      estate: "Cappellano",
      region: "Serralunga d'Alba, Barolo, Piedmont",
      country: "Italy",
      grapes: "Nebbiolo, Barbera",
      favorite: "",
      why: "I've come to love the family's wines and the way of thinking behind them — the tradition, and the refusal to let it be flattened into a product.",
      link: "https://www.cappellano1870.it",
      tags: ["traditional", "ungrafted"],
    },
    {
      name: "Brovia",
      group: "Piedmont & Valtellina",
      estate: "Brovia",
      region: "Castiglione Falletto, Barolo, Piedmont",
      country: "Italy",
      grapes: "Nebbiolo, Barbera, Dolcetto",
      favorite: "",
      why: "I'm a longtime admirer of the family's traditional approach — botti ageing and single-cru Barolos from Rocche di Castiglione, Villero, Brea and Garblèt Sué.",
      link: "https://www.brovia.net",
      tags: ["traditional", "single vineyard"],
    },
    {
      name: "Castello di Verduno",
      group: "Piedmont & Valtellina",
      estate: "Castello di Verduno",
      region: "Verduno, Barolo, Piedmont",
      country: "Italy",
      grapes: "Nebbiolo, Pelaverga",
      favorite: "",
      why: "TODO",
      link: "",
      tags: ["traditional"],
    },
    {
      name: "Olek Bondonio",
      group: "Piedmont & Valtellina",
      estate: "Olek Bondonio",
      region: "Barbaresco, Piedmont",
      country: "Italy",
      grapes: "Nebbiolo, Pelaverga",
      favorite: "",
      why: "TODO",
      link: "",
      tags: ["small grower"],
    },
    {
      name: "Ferrando family",
      group: "Piedmont & Valtellina",
      estate: "Ferrando",
      region: "Carema, Piedmont",
      country: "Italy",
      grapes: "Nebbiolo, Erbaluce",
      favorite: "",
      why: "TODO",
      link: "",
      tags: ["mountain", "terraces"],
    },
    {
      name: "Rivella family",
      group: "Piedmont & Valtellina",
      estate: "Serafino Rivella",
      region: "Barbaresco (Montestefano), Piedmont",
      country: "Italy",
      grapes: "Nebbiolo, Dolcetto",
      favorite: "",
      why: "I have great admiration for an estate that works a single cru with such focus and care, generation after generation.",
      link: "",
      tags: ["single vineyard", "traditional"],
    },
    {
      name: "Fabio Alessandria",
      group: "Piedmont & Valtellina",
      estate: "G.B. Burlotto",
      region: "Verduno, Barolo, Piedmont",
      country: "Italy",
      grapes: "Nebbiolo, Pelaverga",
      favorite: "",
      why: "I deeply admire the family's traditional, whole-bunch approach and the history behind Monvigliero.",
      link: "https://www.burlotto.com",
      tags: ["traditional", "whole bunch"],
    },
    {
      name: "Alessandria family",
      group: "Piedmont & Valtellina",
      estate: "Fratelli Alessandria",
      region: "Verduno, Barolo, Piedmont",
      country: "Italy",
      grapes: "Nebbiolo, Pelaverga",
      favorite: "",
      why: "I'm particularly drawn to their Verduno Pelaverga and their Monvigliero Barolo.",
      link: "https://www.fratellialessandria.it",
      tags: ["traditional"],
    },
    {
      name: "Mauro Mascarello",
      group: "Piedmont & Valtellina",
      estate: "Giuseppe Mascarello e Figlio",
      region: "Monchiero / Castiglione Falletto, Barolo, Piedmont",
      country: "Italy",
      grapes: "Nebbiolo, Barbera, Dolcetto",
      favorite: "",
      why: "TODO",
      link: "https://www.mascarello1881.com",
      tags: ["traditional", "single vineyard"],
    },
    {
      name: "Pelizzatti Perego family",
      group: "Piedmont & Valtellina",
      estate: "ARPEPE (Ar.Pe.Pe.)",
      region: "Valtellina (Sassella, Grumello, Inferno), Lombardy",
      country: "Italy",
      grapes: "Nebbiolo (Chiavennasca)",
      favorite: "",
      why: "TODO",
      link: "https://www.arpepe.com",
      tags: ["mountain", "terraces", "traditional"],
    },

    // ── Central & southern Italy ────────────────────────────
    {
      name: "Monteraponi",
      group: "Central & southern Italy",
      estate: "Monteraponi",
      region: "Radda in Chianti, Chianti Classico, Tuscany",
      country: "Italy",
      grapes: "Sangiovese, Canaiolo, Trebbiano",
      favorite: "",
      why: "My passion for Sangiovese — and especially for how it evolves over time.",
      link: "https://www.monteraponi.it",
      tags: ["organic", "high altitude"],
    },
    {
      name: "Martino Manetti",
      group: "Central & southern Italy",
      estate: "Montevertine",
      region: "Radda in Chianti, Tuscany",
      country: "Italy",
      grapes: "Sangiovese, Canaiolo, Colorino",
      favorite: "",
      why: "TODO",
      link: "https://www.montevertine.it",
      tags: ["traditional"],
    },
    {
      name: "Francesco Paolo Valentini",
      group: "Central & southern Italy",
      estate: "Valentini",
      region: "Loreto Aprutino, Abruzzo",
      country: "Italy",
      grapes: "Trebbiano d'Abruzzo, Montepulciano",
      favorite: "",
      why: "TODO",
      link: "",
      tags: ["traditional", "age-worthy"],
    },

    // ── Alto Adige ──────────────────────────────────────────
    {
      name: "Martin Gojer & Marion Untersulzner",
      group: "Alto Adige",
      estate: "Pranzegg",
      region: "Kohlern above Bolzano, Alto Adige",
      country: "Italy",
      grapes: "Vernatsch (Schiava), Lagrein, Gewürztraminer",
      favorite: "",
      why: "TODO",
      link: "https://www.pranzegg.com",
      tags: ["biodynamic", "old vines"],
    },
    {
      name: "Peter Pliger",
      group: "Alto Adige",
      estate: "Kuenhof",
      region: "Valle Isarco (Brixen), Alto Adige",
      country: "Italy",
      grapes: "Riesling, Sylvaner, Grüner Veltliner, Gewürztraminer",
      favorite: "",
      why: "TODO",
      link: "https://www.kuenhof.com",
      tags: ["alpine"],
    },

    // ── Greece, Portugal, Germany, Switzerland ──────────────
    {
      name: "Yannis Economou",
      group: "Greece, Portugal, Germany, Switzerland",
      estate: "Domaine Economou",
      region: "Sitia, eastern Crete",
      country: "Greece",
      grapes: "Liatiko",
      favorite: "",
      why: "I'm drawn to Crete's mountain reds, and this is one of the most singular expressions of Liatiko anywhere — the high-altitude sites and the age-worthiness of the wines especially.",
      link: "",
      tags: ["high altitude", "aged release"],
    },
    {
      name: "Adega Viúva Gomes",
      group: "Greece, Portugal, Germany, Switzerland",
      estate: "Adega Viúva Gomes",
      region: "Colares, Sintra",
      country: "Portugal",
      grapes: "Ramisco, Malvasia de Colares",
      favorite: "",
      why: "Colares and its ungrafted Ramisco — one of the last true sand-planted, phylloxera-free vineyards.",
      link: "https://www.viuvagomes.com",
      tags: ["ungrafted", "sand", "old vines"],
    },
    {
      name: "Erich & Johannes Weber",
      group: "Greece, Portugal, Germany, Switzerland",
      estate: "Hofgut Falkenstein",
      region: "Niedermennig, Saar",
      country: "Germany",
      grapes: "Riesling",
      favorite: "",
      why: "Old-vine, traditionally farmed Saar Riesling from one of the last true cask-by-cask estates in the region.",
      link: "",
      tags: ["old vines", "traditional"],
    },
    {
      name: "Marie-Thérèse Chappaz",
      group: "Greece, Portugal, Germany, Switzerland",
      estate: "Domaine Marie-Thérèse Chappaz",
      region: "Fully, Valais",
      country: "Switzerland",
      grapes: "Petite Arvine, Marsanne (Ermitage), Pinot Noir, Syrah",
      favorite: "",
      why: "Terroir wines from a small biodynamic family estate — her Grain Noble sweet wines have held a special place on my list for a long time.",
      link: "https://www.chappaz.ch",
      tags: ["biodynamic", "sweet"],
    },

    // ── Loire ───────────────────────────────────────────────
    {
      name: "Domaine Ogereau",
      group: "Loire",
      estate: "Domaine Ogereau",
      region: "Saint-Lambert-du-Lattay, Anjou, Loire",
      country: "France",
      grapes: "Chenin Blanc, Cabernet Franc",
      favorite: "",
      why: "TODO",
      link: "https://www.domaineogereau.com",
      tags: ["organic", "sweet"],
    },
    {
      name: "Damien Laureau",
      group: "Loire",
      estate: "Domaine Laureau",
      region: "Savennières, Anjou, Loire",
      country: "France",
      grapes: "Chenin Blanc",
      favorite: "",
      why: "TODO",
      link: "",
      tags: ["schist"],
    },
    {
      name: "Mark & Martial Angeli",
      group: "Loire",
      estate: "La Ferme de la Sansonnière",
      region: "Thouarcé, Anjou, Loire",
      country: "France",
      grapes: "Chenin Blanc",
      favorite: "",
      why: "TODO",
      link: "",
      tags: ["biodynamic", "natural"],
    },
    {
      name: "Romain Guiberteau",
      group: "Loire",
      estate: "Domaine Guiberteau",
      region: "Brézé, Saumur, Loire",
      country: "France",
      grapes: "Chenin Blanc, Cabernet Franc",
      favorite: "",
      why: "TODO",
      link: "",
      tags: ["limestone", "organic"],
    },
    {
      name: "François Chidaine",
      group: "Loire",
      estate: "Domaine François Chidaine",
      region: "Montlouis-sur-Loire, Touraine, Loire",
      country: "France",
      grapes: "Chenin Blanc",
      favorite: "",
      why: "TODO",
      link: "",
      tags: ["biodynamic"],
    },
    {
      name: "Evelyne de Pontbriand",
      group: "Loire",
      estate: "Domaine du Closel (Château des Vaults)",
      region: "Savennières, Anjou, Loire",
      country: "France",
      grapes: "Chenin Blanc",
      favorite: "",
      why: "TODO",
      link: "",
      tags: ["schist"],
    },
    {
      name: "Château Pierre-Bise",
      group: "Loire",
      estate: "Château Pierre-Bise",
      region: "Beaulieu-sur-Layon, Anjou, Loire",
      country: "France",
      grapes: "Chenin Blanc, Cabernet Franc",
      favorite: "",
      why: "TODO",
      link: "https://www.chateaupierrebise.fr",
      tags: ["sweet", "schist"],
    },
    {
      name: "Antoine Gouffier",
      group: "Loire",
      estate: "Domaine du Bouchot",
      region: "Pouilly-Fumé, Loire",
      country: "France",
      grapes: "Sauvignon Blanc",
      favorite: "",
      why: "TODO",
      link: "",
      tags: ["biodynamic"],
    },
    {
      name: "Thibaud Boudignon",
      group: "Loire",
      estate: "Thibaud Boudignon",
      region: "Savennières, Anjou, Loire",
      country: "France",
      grapes: "Chenin Blanc",
      favorite: "",
      why: "TODO",
      link: "",
      tags: ["schist"],
    },

    // ── Jura & Chablis ──────────────────────────────────────
    {
      name: "Laurent & Carmen Macle",
      group: "Jura & Chablis",
      estate: "Domaine Macle",
      region: "Château-Chalon, Jura",
      country: "France",
      grapes: "Savagnin, Chardonnay",
      favorite: "",
      why: "Château-Chalon and the sous-voile Vin Jaune tradition are a big part of why I'm going to the Jura.",
      link: "https://www.domainemacle.fr",
      tags: ["vin jaune", "oxidative", "organic"],
    },
    {
      name: "Julien Labet",
      group: "Jura & Chablis",
      estate: "Domaine Labet",
      region: "Rotalier, Sud Revermont, Jura",
      country: "France",
      grapes: "Chardonnay, Savagnin, Poulsard",
      favorite: "",
      why: "TODO",
      link: "",
      tags: ["natural"],
    },
    {
      name: "Jean-François Ganevat",
      group: "Jura & Chablis",
      estate: "Domaine Ganevat",
      region: "Rotalier, Sud Revermont, Jura",
      country: "France",
      grapes: "Chardonnay, Savagnin, Poulsard",
      favorite: "",
      why: "TODO",
      link: "",
      tags: ["natural", "biodynamic"],
    },
    {
      name: "Kenjiro Kagami",
      group: "Jura & Chablis",
      estate: "Domaine des Miroirs",
      region: "Grusse, Jura",
      country: "France",
      grapes: "Chardonnay, Savagnin, Poulsard",
      favorite: "",
      why: "TODO",
      link: "",
      tags: ["natural"],
    },
    {
      name: "Alice & Olivier De Moor",
      group: "Jura & Chablis",
      estate: "Alice & Olivier De Moor",
      region: "Courgis, Chablis, Burgundy",
      country: "France",
      grapes: "Chardonnay, Aligoté",
      favorite: "",
      why: "TODO",
      link: "",
      tags: ["organic", "natural"],
    },

    // ── Mature Southwest & Languedoc (my palate brief to La Tour d'Argent) ──
    {
      name: "Olivier Jullien",
      group: "Mature Southwest & Languedoc",
      estate: "Mas Jullien",
      region: "Terrasses du Larzac, Languedoc",
      country: "France",
      grapes: "Carignan, Mourvèdre, Syrah, Grenache",
      favorite: "",
      why: "I gravitate toward complexity and balance rather than sheer power — ideally with real bottle age (1990s or 2000s) already showing leather, dried fruit, mineral and forest floor.",
      link: "",
      tags: ["age-worthy"],
    },
    {
      name: "Sylvain Fadat",
      group: "Mature Southwest & Languedoc",
      estate: "Domaine d'Aupilhac",
      region: "Montpeyroux, Languedoc",
      country: "France",
      grapes: "Carignan, Mourvèdre, Syrah",
      favorite: "",
      why: "Age-worthy and less obvious than the trophy regions — complexity and balance over power, ideally with 1990s or 2000s bottle age.",
      link: "",
      tags: ["age-worthy"],
    },
    {
      name: "Laurent Vaillé",
      group: "Mature Southwest & Languedoc",
      estate: "La Grange des Pères",
      region: "Aniane, Languedoc",
      country: "France",
      grapes: "Syrah, Mourvèdre, Cabernet Sauvignon",
      favorite: "",
      why: "Age-worthy and less obvious than the trophy regions — complexity and balance over power, ideally with 1990s or 2000s bottle age.",
      link: "",
      tags: ["age-worthy"],
    },
    {
      name: "Henri Ramonteu",
      group: "Mature Southwest & Languedoc",
      estate: "Domaine Cauhapé",
      region: "Jurançon, South West France",
      country: "France",
      grapes: "Petit Manseng, Gros Manseng",
      favorite: "",
      why: "Jurançon with real bottle age — and I'm happy to go for a moelleux.",
      link: "",
      tags: ["sweet", "age-worthy"],
    },
    {
      name: "Marie Hours",
      group: "Mature Southwest & Languedoc",
      estate: "Clos Uroulat",
      region: "Jurançon, South West France",
      country: "France",
      grapes: "Petit Manseng, Gros Manseng",
      favorite: "",
      why: "Jurançon with real bottle age — and I'm happy to go for a moelleux.",
      link: "",
      tags: ["sweet", "age-worthy"],
    },
    {
      name: "Alain Brumont",
      group: "Mature Southwest & Languedoc",
      estate: "Château Montus / Château Bouscassé",
      region: "Madiran, South West France",
      country: "France",
      grapes: "Tannat",
      favorite: "",
      why: "Age-worthy and less obvious than the trophy regions — I want it with real bottle age, 1990s or 2000s.",
      link: "",
      tags: ["age-worthy", "tannic"],
    },
  ],

  quotes: [
    {
      text: "The way we spend our days is, of course, how we spend our lives.",
      author: "Annie Dillard",
      source: "The Writing Life",
    },
    {
      text: "Wine is bottled poetry.",
      author: "Robert Louis Stevenson",
      source: "",
    },
    {
      text: "Beauty is an experience, nothing else. It is not a fact or a definite thing.",
      author: "Agnes Martin",
      source: "",
    },
    {
      text: "Everything you can imagine is real.",
      author: "Pablo Picasso",
      source: "",
    },
    {
      text: "Attention is the rarest and purest form of generosity.",
      author: "Simone Weil",
      source: "",
    },
  ],
};
